### ISSUE TITLE
Parameter-Validation example error 'stoi' is not a member of 'std' 

### ISSUE THREAD

**Issue by ghost** [fhessel/esp32_https_server#115]
Goal: Compile the example included called Parameter-Validation.

After changing the network login information, the compile process gives the following error:

'stoi' is not a member of 'std' 

**ESP32 Module**
Standard Doit 

**Software (please complete the following information if applicable)**
 Arduino ide

Wondering if I am missing a library.  I tried string.h but that did not help.

Regards,
BCGuy

**Comment by fhessel** [comment]
Hi, thanks for your report! I can reproduce that for the Arduino IDE as well as for PlatformIO.

The problem here is that the version of the C++ standard library shipped with the Arduino Core for the ESP32 does not define `_GLIBCXX_USE_C99`, which results in having only limited access to functions like `std::stoi` or `std::stoul` (you'll get the same error for `stoul` when you fix the other one).

Getting these functions running within the Arduino IDE won't make fun, and even though it's easier in PIO, it might have a lot of undesired side effects.

So what I'd suggest would be using the internal util functions from this library:

```C++
// Change the line in handleSwitch:
LED * led = &myLEDs[parseUInt(params->getPathParameter(0))];

// Rewrite validateLEDID as follows:
bool validateLEDID(std::string s) {
  uint32_t id = parseUInt(s, 0xffffffff); // convert to number (failure will give 0, or 0xffffffff if number is too big)
  return id < LEDCOUNT && (id != 0 || s=="0"); // check that LEDCOUNT isn't exceeded, and if we have a 0, make sure it isn't caused by a failure.
}
```

I'll leave this issue open as long as the example isn't fixed. I'm not really happy with the implementation of the additional checks in the second function...

**Comment by ghost** [comment]
That got it working.

Thank you

**Comment by ghost** [comment]
Thank you for your prompt and professional response.  This is my first
interaction with Github and it appears to me that I should not have
hesitated.

Kind regards,

BCGuy
