### ISSUE TITLE
Wont work when bluetooth is started

### ISSUE THREAD

**Issue by jmiranda7777** [fhessel/esp32_https_server#56]
Everything works great until I start

  pServer = BLEDevice::createServer();

I can include the files
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
and it works unless I start bluetooth.
There is some kind of conflict but i haven't been able to figure it out.
I am using partition min sips with OTA and I am only 88%. Its not crashes I see the message about web hits but there are errors starting ssl

**Comment by fhessel** [comment]
Hi,

could you please provide some infos about your environment (Arduino
IDE/Platform IO) and the versions of the tools you're using?

And if you're using PlatformIO, could you please enable full logging on
DEBUG (see bottom of the repo's readme file) and attach the output?

jmiranda7777 <notifications@github.com> schrieb am Di., 12. Nov. 2019,
18:35:

**Comment by jmiranda7777** [comment]
arduino ide 1.8.9
board nano32s
partition min spiff
I haven't done much 
Here is the Arduino code see if it reproduces the issue for you

[min32SSL.zip](https://github.com/fhessel/esp32_https_server/files/3837984/min32SSL.zip)

**Comment by fhessel** [comment]
It's a memory issue. Every TLS connection needs roughly 40-50k of large blocks on the heap, which isn't free after initializing Bluetooth. I tested a minimal example on the WROOM-32 (the common DevBoard) and on a custom board with a [WROVER chip](https://eu.mouser.com/ProductDetail/espressif/esp32-wrover-b-16mb/?qs=w%2Fv1CP2dgqrsSzc2ZlAxuA==). You'll find the sketch and the output below. I think, the results will be similar for your project, even though I used PIO.

**Project Files**

<details>
<summary>main.cpp</summary>

```c++
#include <Arduino.h>

#define WIFI_SSID "..."
#define WIFI_PSK "..."

#include "cert.h"
#include "private_key.h"
#include "favicon.h"

#include <WiFi.h>

#include <HTTPSServer.hpp>
#include <SSLCert.hpp>
#include <HTTPRequest.hpp>
#include <HTTPResponse.hpp>

#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

using namespace httpsserver;

SSLCert cert = SSLCert(
  example_crt_DER, example_crt_DER_len,
  example_key_DER, example_key_DER_len
);

HTTPSServer secureServer = HTTPSServer(&cert);

void handleRoot(HTTPRequest * req, HTTPResponse * res);
void handleFavicon(HTTPRequest * req, HTTPResponse * res);
void handle404(HTTPRequest * req, HTTPResponse * res);

unsigned long lastReconnect = 0;

void setup() {
  // For logging
  Serial.begin(115200);

  // Connect to WiFi
  Serial.println("Setting up WiFi");
  WiFi.begin(WIFI_SSID, WIFI_PSK);
  while (WiFi.status() != WL_CONNECTED) {
    if (millis()-lastReconnect > 10000) {
      lastReconnect = millis();
      WiFi.disconnect();
      delay(500);
      Serial.print(":");
      WiFi.begin(WIFI_SSID, WIFI_PSK);
    } else {
      delay(500);
      Serial.print(".");
    }
  }
  Serial.print("Connected. IP=");
  Serial.println(WiFi.localIP());

  ResourceNode * nodeRoot    = new ResourceNode("/", "GET", &handleRoot);
  ResourceNode * nodeFavicon = new ResourceNode("/favicon.ico", "GET", &handleFavicon);
  ResourceNode * node404     = new ResourceNode("", "GET", &handle404);
  secureServer.registerNode(nodeRoot);
  secureServer.registerNode(nodeFavicon);
  secureServer.setDefaultNode(node404);

  Serial.println("Starting server...");
  secureServer.start();
  if (secureServer.isRunning()) {
	  Serial.println("Server ready.");
  }
}

BLEServer *pServer;
unsigned long lastTimestamp = 0;

void loop() {
  secureServer.loop();
  
  if (lastTimestamp + 1000 < millis()) {
    Serial.printf("Timestamp: %lu ms\n", millis());
    Serial.printf("Free Heap: %u bytes\n", esp_get_free_heap_size());
    lastTimestamp = millis();
  }

  if (WiFi.status() != WL_CONNECTED) {
    if (millis()-lastReconnect > 10000) {
      Serial.println("Connection lost, reconnecting...");
      WiFi.disconnect();
      delay(500);
      WiFi.begin(WIFI_SSID, WIFI_PSK);
      lastReconnect = millis();
    }
  }

  if(Serial.available() && Serial.read()=='b' && pServer==NULL) {
    Serial.println("Starting BT...");
    BLEDevice::init("myESP");
    pServer = BLEDevice::createServer();
    Serial.println("Started BT...");
  }
}

void handleRoot(HTTPRequest * req, HTTPResponse * res) {
  // see "Static Page" example
}

void handleFavicon(HTTPRequest * req, HTTPResponse * res) {
  // see "Static Page" example
}

void handle404(HTTPRequest * req, HTTPResponse * res) {
  // see "Static Page" example
}

```

</details>

<details>
<summary>platform.ini</summary>

```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions_custom.csv
build_flags =
  -DBOARD_HAS_PSRAM ; <- only for WROVER
  -DHTTPS_LOGLEVEL=3
  -DHTTPS_LOGTIMESTAMP
```

</details>

<details>
<summary>partitions_custom.csv</summary>

```
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x1E0000,
app1,     app,  ota_1,   0x1F0000,0x1E0000,
spiffs,   data, spiffs,  0x3D0000,0x30000,
```

</details>

**Log Output**

<details>
<summary>ESP32 WROOM with built-in RAM</summary>

```
Free Heap: 145828 bytes
[HTTPS:I:      8359] New connection. Socket FID=55
Free Heap: 103316 bytes
[HTTPS:I:     10052] Request: GET / (FID=55)
[HTTPS:I:     10063] Connection closed. Socket FID=55
Free Heap: 144628 bytes
Free Heap: 144628 bytes
Starting BT...
Started BT...
Free Heap: 52380 bytes
[HTTPS:I:     18904] New connection. Socket FID=56
[HTTPS:E:     19412] SSL_accept failed. Aborting handshake. FID=56
[HTTPS:I:     19413] Connection closed. Socket FID=56
Free Heap: 51356 bytes
```

</details>

<details>
<summary>ESP32 WROVER with 4MB extenral PSRAM and <tt>BOARD_HAS_PSRAM</tt> set</summary>

```
Free Heap: 4339764 bytes
[HTTPS:I:      9615] New connection. Socket FID=55
Timestamp: 11234 ms
Free Heap: 4297584 bytes
[HTTPS:I:     11283] Request: GET / (FID=55)
[HTTPS:I:     11296] Connection closed. Socket FID=55
Free Heap: 4338552 bytes
Starting BT...
Started BT...
Free Heap: 4246292 bytes
[HTTPS:I:     17702] New connection. Socket FID=56
Free Heap: 4204760 bytes
[HTTPS:I:     19971] Request: GET / (FID=56)
[HTTPS:I:     19984] Connection closed. Socket FID=56
Free Heap: 4245748 bytes
```

</details>

As it's clearly visible, on the WROOM, only 51356 bytes of heap memory remain after initializing BLE. That's not sufficient to do the TLS handshake, and there is nothing I can do about it, as it's an atomic call to the openSSL implementation of the underlying esp-idf.

You also can see that enabling PSRAM solves that problem on the WROVER.

What you can do:

- Use `HTTPServer` instead of `HTTPSServer`, but you don't have encryption and authentication then.
- Try smaller certificates (maybe I also give that a try later on), but you most likely won't get over a single "concurrent" connection.
- Use another ESP32 module. If you're designing custom hardware, you usually replace your DevBoard with a custom PCB at some time, so you can just pick an ESP module with additional RAM (and maybe also flash, to circumvent the problem with the huge BLE library). Meanwhile, you'll also find DevBoards with more memory, look for "PSRAM".

I know that answer's not very satisfying, so I you have another idea to discuss here, let me know. Otherwise I'd close the issue, as I cannot act on it meaningfully.

**Comment by jmiranda7777** [comment]
You can close the bug.
Thank you so much for the answer I will look for a Dev Board with more working memory.
The SSL works really well. The bluetooth on the chip needs a lot of work its way too heavy.
Thank you for all your support.
Jorge
